language: node_js
node_js:
  - "node"
env:
  - MY_VAR=EverythignIsAwesome
before_script:
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - uname -a 
  - . branch.sh
  - curl -s -o /dev/null -I -w "%{http_code}" https://ademo.app

  - if [ $TRAVIS_PULL_REQUEST_BRANCH ]; then
      echo "Totes on a Branch! $TRAVIS_PULL_REQUEST_BRANCH";
      # https://stackoverflow.com/questions/229551/string-contains-in-bash
      reg="issue#";
      if [[ $TRAVIS_PULL_REQUEST_BRANCH =~ $reg ]]; then
        echo "This is a pull request with an issue";
        IFS=@ read left right <<< "$string";
        echo "$right"
      fi
      URL="https://${TRAVIS_PULL_REQUEST_BRANCH}.ademo.app";
      echo $URL;
      STATUS=$(curl -s -o /dev/null -I -w "%{http_code}" $URL);
      echo $STATUS;
    fi