language: node_js
node_js:
  - "node"
env:
  - MY_VAR=EverythignIsAwesome
before_script:
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - uname -a 
  - . branch.sh
  - curl -s -o /dev/null -I -w "%{http_code}" http://www.example.org
  - if [ $TRAVIS_PULL_REQUEST_BRANCH ]; then
      echo "Totes on a Branch!"
      curl -s -o /dev/null -I -w "%{http_code}" http://www.example.org
    fi